// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl09iw4WyHUyT8lc8HHoKPSMQ4GZNjOWE',
    appId: '1:1040660131401:web:1149681ad8ee6f0a9b9998',
    messagingSenderId: '1040660131401',
    projectId: 'sunshine-cleanest',
    authDomain: 'sunshine-cleanest.firebaseapp.com',
    databaseURL: 'https://sunshine-cleanest-default-rtdb.firebaseio.com',
    storageBucket: 'sunshine-cleanest.appspot.com',
    measurementId: 'G-LQMMEGX1QP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBUBXnrg7SV107VCcNiH4TsazCH-61HCdA',
    appId: '1:1040660131401:android:dd7c2fa63aad13b19b9998',
    messagingSenderId: '1040660131401',
    projectId: 'sunshine-cleanest',
    databaseURL: 'https://sunshine-cleanest-default-rtdb.firebaseio.com',
    storageBucket: 'sunshine-cleanest.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDX-igq-YqM0Gstb04XsRbyBLCW9NazZ5Y',
    appId: '1:1040660131401:ios:3e66e20b8e4705f39b9998',
    messagingSenderId: '1040660131401',
    projectId: 'sunshine-cleanest',
    databaseURL: 'https://sunshine-cleanest-default-rtdb.firebaseio.com',
    storageBucket: 'sunshine-cleanest.appspot.com',
    iosClientId: '1040660131401-96qp5ivss7jg3tmbqq70jqd2j30kbdo9.apps.googleusercontent.com',
    iosBundleId: 'com.google.obligatoryofficiality.sunshineCleanest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDX-igq-YqM0Gstb04XsRbyBLCW9NazZ5Y',
    appId: '1:1040660131401:ios:3e66e20b8e4705f39b9998',
    messagingSenderId: '1040660131401',
    projectId: 'sunshine-cleanest',
    databaseURL: 'https://sunshine-cleanest-default-rtdb.firebaseio.com',
    storageBucket: 'sunshine-cleanest.appspot.com',
    iosClientId: '1040660131401-96qp5ivss7jg3tmbqq70jqd2j30kbdo9.apps.googleusercontent.com',
    iosBundleId: 'com.google.obligatoryofficiality.sunshineCleanest',
  );
}
